version: "3.9"
services:
  attendance:
    build: .
    container_name: attendance_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app/data:/app/app/data